import { PosterConfig, PosterScene } from '../types';

export const TIMES = {
  dawn: { name: '晨曦', ink: '#201814', paper: '#f4ede1' },
  day: { name: '白昼', ink: '#1c1612', paper: '#faf4ea' },
  dusk: { name: '黄昏', ink: '#241a14', paper: '#faece0' },
  night: { name: '星夜', ink: '#ecdfcf', paper: '#10141b' },
};

export const TERRAINS = {
  plain: { name: '平原' },
  mountain: { name: '群山' },
  water: { name: '江湖' },
  city: { name: '古城' },
  bamboo: { name: '竹林' },
  desert: { name: '大漠' },
};

export const WEATHERS = {
  none: '无',
  rain: '细雨',
  snow: '飞雪',
  leaf: '落叶',
  petal: '花瓣',
};

export const LAYOUTS = {
  popH: '错落横排',
  vertical: '竖排长题',
  stair: '阶梯落字',
  card: '宣纸卡片',
  fan: '扇面题画',
  scroll: '手卷横批',
};

export const WALKERS = {
  scholar: '书生 (长衫·书箱)',
  traveler: '背包客 (现代)',
  monk: '行脚僧 (斗笠·锡杖)',
  girl: '汉服少女 (飘带)',
  classic: '原版小人 (保持原形态)',
};

export const WALKER_DESCRIPTIONS: Record<string, string> = {
  scholar: '长衫飘逸，负笈书箱，步伐从容文雅，尽显东方文人墨客气度。',
  traveler: '现代行囊，连帽卫衣，步履轻快自信，适合都市远行与探索金句。',
  monk: '斗笠遮颜，手持九环锡杖，步履沉稳坚定，兼济沧海普度之韵。',
  girl: '对襟襦裙，云鬓披帛，灵动娇憨，步生春色，随风拂动。',
  classic: '保留原版纯粹线条骨骼与反相摆臂，大巧若拙，自然起伏。',
};

export const HATS = {
  auto: '随人物默认',
  none: '无帽子',
  straw: '草帽',
  bamboo: '逍遥斗笠',
  cap: '鸭舌帽',
};

export const COMPANIONS = {
  none: '无伙伴',
  dog: '小狗 (小跑随行摇尾)',
  bird: '小鸟 (飞落肩头环绕)',
};

export const DECORS: Record<string, string> = {
  sign: '路牌',
  tree: '杂树',
  pine: '松树',
  willow: '垂柳',
  plum: '梅花',
  grass: '草丛',
  stones: '石头',
  flowers: '野花',
  pavilion: '凉亭',
  bridge: '拱桥',
  paifang: '牌坊',
  lanternPole: '灯笼杆',
  milestone: '里程碑',
  boat: '小舟',
  pagoda: '远塔',
  birds: '飞鸟',
  geese: '雁阵',
  butterfly: '蝴蝶',
  kite: '纸鸢',
  skyLantern: '孔明灯',
  fireflies: '萤火',
};

export const CHAPTER_LABELS = [
  '其一', '其二', '其三', '其四', '其五',
  '其六', '其七', '其八', '其九', '其十',
  '十一', '十二', '十三', '十四', '十五'
];

export const PRESET_QUOTES: Omit<PosterScene, 'id' | 'label' | 'width'>[] = [
  {
    name: '道德经',
    quote: '千里之行',
    sub: '始于足下。',
    source: '——《道德经》',
    seal: '道',
    time: 'day',
    terrain: 'plain',
    weather: 'none',
    layout: 'popH',
    decor: ['sign', 'tree', 'grass', 'birds', 'flowers', 'milestone'],
    image: 'builtin:1',
  },
  {
    name: '离骚',
    quote: '路漫漫其修远兮',
    sub: '吾将上下而求索。',
    source: '—— 屈原《离骚》',
    seal: '骚',
    time: 'dusk',
    terrain: 'mountain',
    weather: 'leaf',
    layout: 'vertical',
    decor: ['sign', 'pine', 'stones', 'geese', 'pagoda', 'paifang'],
    image: 'builtin:2',
  },
  {
    name: '终南别业',
    quote: '行到水穷处',
    sub: '坐看云起时。',
    source: '—— 王维《终南别业》',
    seal: '维',
    time: 'day',
    terrain: 'water',
    weather: 'none',
    layout: 'fan',
    decor: ['sign', 'willow', 'boat', 'bridge', 'butterfly', 'grass'],
    image: 'builtin:3',
  },
  {
    name: '定风波',
    quote: '莫听穿林打叶声',
    sub: '何妨吟啸且徐行。',
    source: '—— 苏轼《定风波》',
    seal: '坡',
    time: 'dawn',
    terrain: 'bamboo',
    weather: 'rain',
    layout: 'card',
    decor: ['sign', 'pavilion', 'stones', 'grass'],
    image: 'builtin:4',
  },
  {
    name: '行路难',
    quote: '长风破浪会有时',
    sub: '直挂云帆济沧海。',
    source: '—— 李白《行路难》',
    seal: '白',
    time: 'night',
    terrain: 'city',
    weather: 'none',
    layout: 'scroll',
    decor: ['sign', 'lanternPole', 'plum', 'skyLantern', 'fireflies', 'kite'],
    image: 'builtin:5',
  },
  {
    name: '将进酒',
    quote: '天生我材必有用',
    sub: '千金散尽还复来。',
    source: '—— 李白《将进酒》',
    seal: '酒',
    time: 'dusk',
    terrain: 'desert',
    weather: 'none',
    layout: 'stair',
    decor: ['sign', 'stones', 'geese', 'milestone'],
    image: 'builtin:2',
  },
  {
    name: '题西林壁',
    quote: '不识庐山真面目',
    sub: '只缘身在此山中。',
    source: '—— 苏轼《题西林壁》',
    seal: '山',
    time: 'day',
    terrain: 'mountain',
    weather: 'none',
    layout: 'vertical',
    decor: ['sign', 'pine', 'birds', 'pagoda'],
    image: 'builtin:1',
  },
  {
    name: '游山西村',
    quote: '山重水复疑无路',
    sub: '柳暗花明又一村。',
    source: '—— 陆游《游山西村》',
    seal: '游',
    time: 'day',
    terrain: 'water',
    weather: 'petal',
    layout: 'popH',
    decor: ['sign', 'willow', 'bridge', 'flowers', 'butterfly', 'boat'],
    image: 'builtin:3',
  },
  {
    name: '登鹳雀楼',
    quote: '欲穷千里目',
    sub: '更上一层楼。',
    source: '—— 王之涣《登鹳雀楼》',
    seal: '楼',
    time: 'dusk',
    terrain: 'city',
    weather: 'none',
    layout: 'fan',
    decor: ['sign', 'paifang', 'geese', 'pagoda'],
    image: 'builtin:5',
  },
  {
    name: '江雪',
    quote: '孤舟蓑笠翁',
    sub: '独钓寒江雪。',
    source: '—— 柳宗元《江雪》',
    seal: '雪',
    time: 'night',
    terrain: 'water',
    weather: 'snow',
    layout: 'card',
    decor: ['sign', 'boat', 'pine', 'stones'],
    image: 'builtin:4',
  },
  {
    name: '竹里馆',
    quote: '深林人不知',
    sub: '明月来相照。',
    source: '—— 王维《竹里馆》',
    seal: '竹',
    time: 'night',
    terrain: 'bamboo',
    weather: 'none',
    layout: 'scroll',
    decor: ['sign', 'fireflies', 'stones', 'pavilion'],
    image: 'builtin:4',
  },
  {
    name: '论语',
    quote: '士不可以不弘毅',
    sub: '任重而道远。',
    source: '——《论语·泰伯》',
    seal: '仁',
    time: 'dawn',
    terrain: 'plain',
    weather: 'none',
    layout: 'stair',
    decor: ['sign', 'tree', 'milestone', 'birds', 'grass'],
    image: 'builtin:1',
  },
];

export const DEFAULT_CONFIG: PosterConfig = {
  title: '行者 · 金句漫游',
  subtitle: '一直走的海报',
  speed: 150,
  seed: 42,
  walker: {
    style: 'scholar',
    size: 1,
    hat: 'auto',
    staff: true,
    scarf: true,
    umbrella: 'auto',
    lantern: 'auto',
    companion: 'dog',
  },
  show: {
    intro: true,
    footprints: true,
    infobar: true,
  },
  scenes: [
    {
      id: 'sc1',
      label: '其一',
      name: '道德经',
      quote: '千里之行',
      sub: '始于足下。',
      source: '——《道德经》',
      seal: '道',
      layout: 'popH',
      time: 'day',
      terrain: 'plain',
      weather: 'none',
      decor: ['sign', 'tree', 'grass', 'birds', 'flowers', 'milestone'],
      image: 'builtin:1',
      width: 1400,
    },
    {
      id: 'sc2',
      label: '其二',
      name: '离骚',
      quote: '路漫漫其修远兮',
      sub: '吾将上下而求索。',
      source: '—— 屈原《离骚》',
      seal: '骚',
      layout: 'vertical',
      time: 'dusk',
      terrain: 'mountain',
      weather: 'leaf',
      decor: ['sign', 'pine', 'stones', 'geese', 'pagoda', 'paifang'],
      image: 'builtin:2',
      width: 1400,
    },
    {
      id: 'sc3',
      label: '其三',
      name: '终南别业',
      quote: '行到水穷处',
      sub: '坐看云起时。',
      source: '—— 王维《终南别业》',
      seal: '维',
      layout: 'fan',
      time: 'day',
      terrain: 'water',
      weather: 'none',
      decor: ['sign', 'willow', 'boat', 'bridge', 'butterfly', 'grass'],
      image: 'builtin:3',
      width: 1400,
    },
    {
      id: 'sc4',
      label: '其四',
      name: '定风波',
      quote: '莫听穿林打叶声',
      sub: '何妨吟啸且徐行。',
      source: '—— 苏轼《定风波》',
      seal: '坡',
      layout: 'card',
      time: 'dawn',
      terrain: 'bamboo',
      weather: 'rain',
      decor: ['sign', 'pavilion', 'stones', 'grass'],
      image: 'builtin:4',
      width: 1400,
    },
    {
      id: 'sc5',
      label: '其五',
      name: '行路难',
      quote: '长风破浪会有时',
      sub: '直挂云帆济沧海。',
      source: '—— 李白《行路难》',
      seal: '白',
      layout: 'scroll',
      time: 'night',
      terrain: 'city',
      weather: 'none',
      decor: ['sign', 'lanternPole', 'plum', 'skyLantern', 'fireflies', 'kite'],
      image: 'builtin:5',
      width: 1400,
    },
  ],
};
